apiVersion: v1
kind: Namespace
metadata:
  name: angular
---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: angular-app-replication-set
  namespace: angular
  labels: 
    app:  angular-app-pod  
spec:
  replicas: 2
  selector:
    app:  angular-app-pod
  template:
    metadata:
      name: angular-app-pod
      labels:
        app: angular-app-pod
    spec:
      containers:
      - name: angular-app-container
        image: angular-app:latest
        imagePullPolicy: Never #To make sure to get the image from local docker
        env:
        - name: Database__ConnectionString
          value: "Server=10.112.209.26;Database=WebApiAndSPA;User Id=sa;Password=sa;"
        - name: Hosting__HostName
          value: "localhost"
        - name: Hosting__Port
          value: "30003"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
  namespace: angular
  labels:
    app: angular-app-pod
spec:
  type: NodePort
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 80
    nodePort: 30003
  selector:
    app: angular-app-pod