apiVersion: v1
kind: Namespace
metadata:
  name: angularjs
---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: angularjs-app-replication-set
  namespace: angularjs
  labels: 
    app:  angularjs-app-pod  
spec:
  replicas: 2
  selector:
    app:  angularjs-app-pod
  template:
    metadata:
      name: angularjs-app-pod
      labels:
        app: angularjs-app-pod
    spec:
      containers:
      - name: angularjs-app-container
        image: angularjs-app:latest
        imagePullPolicy: Never #To make sure to get the image from local docker
        env:
        - name: Database__ConnectionString
          value: "Server=10.112.209.26;Database=WebApiAndSPA;User Id=sa;Password=sa;"
        - name: Hosting__HostName
          value: "localhost"
        - name: Hosting__Port
          value: "30002"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angularjs-app-service
  namespace: angularjs
  labels:
    app: angularjs-app-pod
spec:
  type: NodePort
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 80
    nodePort: 30002
  selector:
    app: angularjs-app-pod